### ISSUE TITLE
Feature request: move this project to react-native-community

### ISSUE THREAD

**Issue by thymikee** [pvinis/rn-diff-purge#18]
As discussed with @cpojer, it would be great to move this project to https://github.com/react-native-community so it's a bit more official :)

**Comment by cpojer** [comment]
Yes please! It will make it more accessible for other people to contribute to.

**Comment by pvinis** [comment]
Does someone need to setup the repo for me?

**Comment by cpojer** [comment]
I forked it over to https://github.com/react-native-community/rn-diff-purge and gave you admin permissions. Is there a way you could redirect people coming to this repo there?

**Comment by thymikee** [comment]
He should be able to transfer the repository now (through github settings)

**Comment by thymikee** [comment]
How's this going, any blockers @pvinis?

**Comment by pvinis** [comment]
Purge is officially in rnc as root repo, and this here is a fork of it :D 

The next step is for me to put a link to the rnc repo, which I will do right now.

I did leave this repo because I'm changing the way this generates diffs to make it way better, but I wanted to try it here first. Seems to be fine, so I'll finish up with all the versions, update the readme, and then push everything to rnc/purge.

**Comment by pvinis** [comment]
Woo :D
